version: '3.0'

services:
  crypto-shipping-service:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      EASYPOST_SERVICE_MODE: ${EASYPOST_SERVICE_MODE}
      EASYPOST_API_TOKEN: ${EASYPOST_API_TOKEN}
      NOWPAYMENTS_X_API_TOKEN: ${NOWPAYMENTS_X_API_TOKEN}
      NOWPAYMENTS_X_IPN_SECRET: ${NOWPAYMENTS_X_IPN_SECRET}
    networks:
      - osnet
    ports:
      # http app
      - '8080-8081:8080'
      - '8008-8009:8008'
    volumes:
      - /var/log/crypto-shipping-service:/app/logs:Z
    build:
      context: .
      args:
        APP_VERSION: 0.0.1-SNAPSHOT
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
        reservations:
          cpus: '2'
          memory: '512M'

    extra_hosts:
      - "host.docker.internal:172.17.0.1"
networks:
  osnet:
    driver: bridge
